package spwork;
// Generated 24/11/2015 18:59:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Boleto003 generated by hbm2java
 */
public class Boleto003  implements java.io.Serializable {


     private Long codInstc003;
     private Long codInstcClint003;
     private String amountInCents003;
     private String amountPaidInCents003;
     private String boletoExpirationDate003;
     private String nossoNumero003;
     private String statusChandedDate003;
     private String transactionKey003;
     private String transactionReference003;
     private String previousBoletoTransactionStatus003;
     private String boletoTransactionStatus003;
     private Integer indSit003;
     private Long codInstcUser003;
     private Date datCdm003;
     private Date datUltAlt003;
     private String usrCdm003;
     private String usrUltAlt003;
     private String url003;
     private String codInstcBuy003;
     private java.util.Date datVnc003;

    public Boleto003() {
    }

    public Boleto003(Long codInstcClint003, String amountInCents003, String amountPaidInCents003, String boletoExpirationDate003, String nossoNumero003, String statusChandedDate003, String transactionKey003, String transactionReference003, String previousBoletoTransactionStatus003, String boletoTransactionStatus003, Integer indSit003, Long codInstcUser003, Date datCdm003, Date datUltAlt003, String usrCdm003, String usrUltAlt003) {
       this.codInstcClint003 = codInstcClint003;
       this.amountInCents003 = amountInCents003;
       this.amountPaidInCents003 = amountPaidInCents003;
       this.boletoExpirationDate003 = boletoExpirationDate003;
       this.nossoNumero003 = nossoNumero003;
       this.statusChandedDate003 = statusChandedDate003;
       this.transactionKey003 = transactionKey003;
       this.transactionReference003 = transactionReference003;
       this.previousBoletoTransactionStatus003 = previousBoletoTransactionStatus003;
       this.boletoTransactionStatus003 = boletoTransactionStatus003;
       this.indSit003 = indSit003;
       this.codInstcUser003 = codInstcUser003;
       this.datCdm003 = datCdm003;
       this.datUltAlt003 = datUltAlt003;
       this.usrCdm003 = usrCdm003;
       this.usrUltAlt003 = usrUltAlt003;
    }
   
    public Long getCodInstc003() {
        return this.codInstc003;
    }
    
    public void setCodInstc003(Long codInstc003) {
        this.codInstc003 = codInstc003;
    }
    public Long getCodInstcClint003() {
        return this.codInstcClint003;
    }
    
    public void setCodInstcClint003(Long codInstcClint003) {
        this.codInstcClint003 = codInstcClint003;
    }
    public String getAmountInCents003() {
        return this.amountInCents003;
    }
    
    public void setAmountInCents003(String amountInCents003) {
        this.amountInCents003 = amountInCents003;
    }
    public String getAmountPaidInCents003() {
        return this.amountPaidInCents003;
    }
    
    public void setAmountPaidInCents003(String amountPaidInCents003) {
        this.amountPaidInCents003 = amountPaidInCents003;
    }
    public String getBoletoExpirationDate003() {
        return this.boletoExpirationDate003;
    }
    
    public void setBoletoExpirationDate003(String boletoExpirationDate003) {
        this.boletoExpirationDate003 = boletoExpirationDate003;
    }
    public String getNossoNumero003() {
        return this.nossoNumero003;
    }
    
    public void setNossoNumero003(String nossoNumero003) {
        this.nossoNumero003 = nossoNumero003;
    }
    public String getStatusChandedDate003() {
        return this.statusChandedDate003;
    }
    
    public void setStatusChandedDate003(String statusChandedDate003) {
        this.statusChandedDate003 = statusChandedDate003;
    }
    public String getTransactionKey003() {
        return this.transactionKey003;
    }
    
    public void setTransactionKey003(String transactionKey003) {
        this.transactionKey003 = transactionKey003;
    }
    public String getTransactionReference003() {
        return this.transactionReference003;
    }
    
    public void setTransactionReference003(String transactionReference003) {
        this.transactionReference003 = transactionReference003;
    }
    public String getPreviousBoletoTransactionStatus003() {
        return this.previousBoletoTransactionStatus003;
    }
    
    public void setPreviousBoletoTransactionStatus003(String previousBoletoTransactionStatus003) {
        this.previousBoletoTransactionStatus003 = previousBoletoTransactionStatus003;
    }
    public String getBoletoTransactionStatus003() {
        return this.boletoTransactionStatus003;
    }
    
    public void setBoletoTransactionStatus003(String boletoTransactionStatus003) {
        this.boletoTransactionStatus003 = boletoTransactionStatus003;
    }
    public Integer getIndSit003() {
        return this.indSit003;
    }
    
    public void setIndSit003(Integer indSit003) {
        this.indSit003 = indSit003;
    }
    public Long getCodInstcUser003() {
        return this.codInstcUser003;
    }
    
    public void setCodInstcUser003(Long codInstcUser003) {
        this.codInstcUser003 = codInstcUser003;
    }
    public Date getDatCdm003() {
        return this.datCdm003;
    }
    
    public void setDatCdm003(Date datCdm003) {
        this.datCdm003 = datCdm003;
    }
    public Date getDatUltAlt003() {
        return this.datUltAlt003;
    }
    
    public void setDatUltAlt003(Date datUltAlt003) {
        this.datUltAlt003 = datUltAlt003;
    }
    public String getUsrCdm003() {
        return this.usrCdm003;
    }
    
    public void setUsrCdm003(String usrCdm003) {
        this.usrCdm003 = usrCdm003;
    }
    public String getUsrUltAlt003() {
        return this.usrUltAlt003;
    }
    
    public void setUsrUltAlt003(String usrUltAlt003) {
        this.usrUltAlt003 = usrUltAlt003;
    }

    /**
     * @return the url003
     */
    public String getUrl003() {
        return url003;
    }

    /**
     * @param url003 the url003 to set
     */
    public void setUrl003(String url003) {
        this.url003 = url003;
    }

    /**
     * @return the codInstcBuy003
     */
    public String getCodInstcBuy003() {
        return codInstcBuy003;
    }

    /**
     * @param codInstcBuy003 the codInstcBuy003 to set
     */
    public void setCodInstcBuy003(String codInstcBuy003) {
        this.codInstcBuy003 = codInstcBuy003;
    }

    /**
     * @return the datVnc003
     */
    public java.util.Date getDatVnc003() {
        return datVnc003;
    }

    /**
     * @param datVnc003 the datVnc003 to set
     */
    public void setDatVnc003(java.util.Date datVnc003) {
        this.datVnc003 = datVnc003;
    }




}


