package spwork;
// Generated 24/11/2015 18:59:21 by Hibernate Tools 4.3.1



/**
 * Client001 generated by hbm2java
 */
public class Client001  implements java.io.Serializable {


     private Long codInstc001;
     private String descAbvd001;
     private String desc001;
     private Long tel001;
     private Integer indSit001;
     private Double juros001;

    public Client001() {
    }

    public Client001(String descAbvd001, String desc001, Long tel001, Integer indSit001) {
       this.descAbvd001 = descAbvd001;
       this.desc001 = desc001;
       this.tel001 = tel001;
       this.indSit001 = indSit001;
    }
   
    public Long getCodInstc001() {
        return this.codInstc001;
    }
    
    public void setCodInstc001(Long codInstc001) {
        this.codInstc001 = codInstc001;
    }
    public String getDescAbvd001() {
        return this.descAbvd001;
    }
    
    public void setDescAbvd001(String descAbvd001) {
        this.descAbvd001 = descAbvd001;
    }
    public String getDesc001() {
        return this.desc001;
    }
    
    public void setDesc001(String desc001) {
        this.desc001 = desc001;
    }
    public Long getTel001() {
        return this.tel001;
    }
    
    public void setTel001(Long tel001) {
        this.tel001 = tel001;
    }
    public Integer getIndSit001() {
        return this.indSit001;
    }
    
    public void setIndSit001(Integer indSit001) {
        this.indSit001 = indSit001;
    }

    /**
     * @return the juros
     */
    public Double getJuros001() {
        return juros001;
    }

    /**
     * @param juros the juros to set
     */
    public void setJuros001(Double juros001) {
        this.juros001 = juros001;
    }




}


