package spwork;
// Generated 24/11/2015 18:59:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CreditCard004 generated by hbm2java
 */
public class CreditCard004  implements java.io.Serializable {


     private Long codInstc004;
     private Long codInstcClint004;
     private Long codInstcUser004;
     private String amountInCents004;
     private String authorizedAmountInCents004;
     private String capturedAmountInCents004;
     private String creditCardBrand004;
     private String refundedAmountInCents004;
     private String statusChangedDate004;
     private String transactionIdentifier004;
     private String transactionKey004;
     private String transactionReference004;
     private String uniqueSequentialNumber004;
     private String voidedAmountInCents004;
     private String previousCreditCardTransactionStatus004;
     private String creditCardTransactionStatus004;
     private Integer indSit004;
     private Date datCdm004;
     private Date datUltAlt004;
     private String usrCdm004;
     private String usrUltAlt004;

    public CreditCard004() {
    }

    public CreditCard004(Long codInstcClint004, Long codInstcUser004, String amountInCents004, String authorizedAmountInCents004, String capturedAmountInCents004, String creditCardBrand004, String refundedAmountInCents004, String statusChangedDate004, String transactionIdentifier004, String transactionKey004, String transactionReference004, String uniqueSequentialNumber004, String voidedAmountInCents004, String previousCreditCardTransactionStatus004, String creditCardTransactionStatus004, Integer indSit004, Date datCdm004, Date datUltAlt004, String usrCdm004, String usrUltAlt004) {
       this.codInstcClint004 = codInstcClint004;
       this.codInstcUser004 = codInstcUser004;
       this.amountInCents004 = amountInCents004;
       this.authorizedAmountInCents004 = authorizedAmountInCents004;
       this.capturedAmountInCents004 = capturedAmountInCents004;
       this.creditCardBrand004 = creditCardBrand004;
       this.refundedAmountInCents004 = refundedAmountInCents004;
       this.statusChangedDate004 = statusChangedDate004;
       this.transactionIdentifier004 = transactionIdentifier004;
       this.transactionKey004 = transactionKey004;
       this.transactionReference004 = transactionReference004;
       this.uniqueSequentialNumber004 = uniqueSequentialNumber004;
       this.voidedAmountInCents004 = voidedAmountInCents004;
       this.previousCreditCardTransactionStatus004 = previousCreditCardTransactionStatus004;
       this.creditCardTransactionStatus004 = creditCardTransactionStatus004;
       this.indSit004 = indSit004;
       this.datCdm004 = datCdm004;
       this.datUltAlt004 = datUltAlt004;
       this.usrCdm004 = usrCdm004;
       this.usrUltAlt004 = usrUltAlt004;
    }
   
    public Long getCodInstc004() {
        return this.codInstc004;
    }
    
    public void setCodInstc004(Long codInstc004) {
        this.codInstc004 = codInstc004;
    }
    public Long getCodInstcClint004() {
        return this.codInstcClint004;
    }
    
    public void setCodInstcClint004(Long codInstcClint004) {
        this.codInstcClint004 = codInstcClint004;
    }
    public Long getCodInstcUser004() {
        return this.codInstcUser004;
    }
    
    public void setCodInstcUser004(Long codInstcUser004) {
        this.codInstcUser004 = codInstcUser004;
    }
    public String getAmountInCents004() {
        return this.amountInCents004;
    }
    
    public void setAmountInCents004(String amountInCents004) {
        this.amountInCents004 = amountInCents004;
    }
    public String getAuthorizedAmountInCents004() {
        return this.authorizedAmountInCents004;
    }
    
    public void setAuthorizedAmountInCents004(String authorizedAmountInCents004) {
        this.authorizedAmountInCents004 = authorizedAmountInCents004;
    }
    public String getCapturedAmountInCents004() {
        return this.capturedAmountInCents004;
    }
    
    public void setCapturedAmountInCents004(String capturedAmountInCents004) {
        this.capturedAmountInCents004 = capturedAmountInCents004;
    }
    public String getCreditCardBrand004() {
        return this.creditCardBrand004;
    }
    
    public void setCreditCardBrand004(String creditCardBrand004) {
        this.creditCardBrand004 = creditCardBrand004;
    }
    public String getRefundedAmountInCents004() {
        return this.refundedAmountInCents004;
    }
    
    public void setRefundedAmountInCents004(String refundedAmountInCents004) {
        this.refundedAmountInCents004 = refundedAmountInCents004;
    }
    public String getStatusChangedDate004() {
        return this.statusChangedDate004;
    }
    
    public void setStatusChangedDate004(String statusChangedDate004) {
        this.statusChangedDate004 = statusChangedDate004;
    }
    public String getTransactionIdentifier004() {
        return this.transactionIdentifier004;
    }
    
    public void setTransactionIdentifier004(String transactionIdentifier004) {
        this.transactionIdentifier004 = transactionIdentifier004;
    }
    public String getTransactionKey004() {
        return this.transactionKey004;
    }
    
    public void setTransactionKey004(String transactionKey004) {
        this.transactionKey004 = transactionKey004;
    }
    public String getTransactionReference004() {
        return this.transactionReference004;
    }
    
    public void setTransactionReference004(String transactionReference004) {
        this.transactionReference004 = transactionReference004;
    }
    public String getUniqueSequentialNumber004() {
        return this.uniqueSequentialNumber004;
    }
    
    public void setUniqueSequentialNumber004(String uniqueSequentialNumber004) {
        this.uniqueSequentialNumber004 = uniqueSequentialNumber004;
    }
    public String getVoidedAmountInCents004() {
        return this.voidedAmountInCents004;
    }
    
    public void setVoidedAmountInCents004(String voidedAmountInCents004) {
        this.voidedAmountInCents004 = voidedAmountInCents004;
    }
    public String getPreviousCreditCardTransactionStatus004() {
        return this.previousCreditCardTransactionStatus004;
    }
    
    public void setPreviousCreditCardTransactionStatus004(String previousCreditCardTransactionStatus004) {
        this.previousCreditCardTransactionStatus004 = previousCreditCardTransactionStatus004;
    }
    public String getCreditCardTransactionStatus004() {
        return this.creditCardTransactionStatus004;
    }
    
    public void setCreditCardTransactionStatus004(String creditCardTransactionStatus004) {
        this.creditCardTransactionStatus004 = creditCardTransactionStatus004;
    }
    public Integer getIndSit004() {
        return this.indSit004;
    }
    
    public void setIndSit004(Integer indSit004) {
        this.indSit004 = indSit004;
    }
    public Date getDatCdm004() {
        return this.datCdm004;
    }
    
    public void setDatCdm004(Date datCdm004) {
        this.datCdm004 = datCdm004;
    }
    public Date getDatUltAlt004() {
        return this.datUltAlt004;
    }
    
    public void setDatUltAlt004(Date datUltAlt004) {
        this.datUltAlt004 = datUltAlt004;
    }
    public String getUsrCdm004() {
        return this.usrCdm004;
    }
    
    public void setUsrCdm004(String usrCdm004) {
        this.usrCdm004 = usrCdm004;
    }
    public String getUsrUltAlt004() {
        return this.usrUltAlt004;
    }
    
    public void setUsrUltAlt004(String usrUltAlt004) {
        this.usrUltAlt004 = usrUltAlt004;
    }




}


