package spwork;
// Generated 24/11/2015 18:59:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User002 generated by hbm2java
 */
public class User002  implements java.io.Serializable {


     private Long codInstc002;
     private Long codInstcClint002;
     private String name002;
     private String tel002;
     private String cpf002;
     private Double debt002;
     private String email002;
     private String emailConf002;
     private String mes002;
     private String ano002;
     private Integer indSit002;
     private String prod002;
     private String subProd002;
     private Date datCdm002;
     private Date datUltAlt002;
     private String usrCdm002;
     private String usrUltAlt002;

    public User002() {
    }

    public User002(Long codInstcClint002, String name002, String tel002, String cpf002, Double debt002, String email002, String emailConf002, String mes002, String ano002, Integer indSit002, String prod002, String subProd002, Date datCdm002, Date datUltAlt002, String usrCdm002, String usrUltAlt002) {
       this.codInstcClint002 = codInstcClint002;
       this.name002 = name002;
       this.tel002 = tel002;
       this.cpf002 = cpf002;
       this.debt002 = debt002;
       this.email002 = email002;
       this.emailConf002 = emailConf002;
       this.mes002 = mes002;
       this.ano002 = ano002;
       this.indSit002 = indSit002;
       this.prod002 = prod002;
       this.subProd002 = subProd002;
       this.datCdm002 = datCdm002;
       this.datUltAlt002 = datUltAlt002;
       this.usrCdm002 = usrCdm002;
       this.usrUltAlt002 = usrUltAlt002;
    }
   
    public Long getCodInstc002() {
        return this.codInstc002;
    }
    
    public void setCodInstc002(Long codInstc002) {
        this.codInstc002 = codInstc002;
    }
    public Long getCodInstcClint002() {
        return this.codInstcClint002;
    }
    
    public void setCodInstcClint002(Long codInstcClint002) {
        this.codInstcClint002 = codInstcClint002;
    }
    public String getName002() {
        return this.name002;
    }
    
    public void setName002(String name002) {
        this.name002 = name002;
    }
    public String getTel002() {
        return this.tel002;
    }
    
    public void setTel002(String tel002) {
        this.tel002 = tel002;
    }
    public String getCpf002() {
        return this.cpf002;
    }
    
    public void setCpf002(String cpf002) {
        this.cpf002 = cpf002;
    }
    public Double getDebt002() {
        return this.debt002;
    }
    
    public void setDebt002(Double debt002) {
        this.debt002 = debt002;
    }
    public String getEmail002() {
        return this.email002;
    }
    
    public void setEmail002(String email002) {
        this.email002 = email002;
    }
    public String getEmailConf002() {
        return this.emailConf002;
    }
    
    public void setEmailConf002(String emailConf002) {
        this.emailConf002 = emailConf002;
    }
    public String getMes002() {
        return this.mes002;
    }
    
    public void setMes002(String mes002) {
        this.mes002 = mes002;
    }
    public String getAno002() {
        return this.ano002;
    }
    
    public void setAno002(String ano002) {
        this.ano002 = ano002;
    }
    public Integer getIndSit002() {
        return this.indSit002;
    }
    
    public void setIndSit002(Integer indSit002) {
        this.indSit002 = indSit002;
    }
    public String getProd002() {
        return this.prod002;
    }
    
    public void setProd002(String prod002) {
        this.prod002 = prod002;
    }
    public String getSubProd002() {
        return this.subProd002;
    }
    
    public void setSubProd002(String subProd002) {
        this.subProd002 = subProd002;
    }
    public Date getDatCdm002() {
        return this.datCdm002;
    }
    
    public void setDatCdm002(Date datCdm002) {
        this.datCdm002 = datCdm002;
    }
    public Date getDatUltAlt002() {
        return this.datUltAlt002;
    }
    
    public void setDatUltAlt002(Date datUltAlt002) {
        this.datUltAlt002 = datUltAlt002;
    }
    public String getUsrCdm002() {
        return this.usrCdm002;
    }
    
    public void setUsrCdm002(String usrCdm002) {
        this.usrCdm002 = usrCdm002;
    }
    public String getUsrUltAlt002() {
        return this.usrUltAlt002;
    }
    
    public void setUsrUltAlt002(String usrUltAlt002) {
        this.usrUltAlt002 = usrUltAlt002;
    }




}


